### ISSUE TITLE
Can't authorize device

### ISSUE THREAD

**Issue by DemirG** [jellyfin/jellyfin-plugin-trakt#177] opened 2022-10-18 07:41 UTC
Hi,

I'm having problems with Trakt not willing to authorize my jellyfin deivce. Have tried deleting trakt.xml and the plugin folder, then re-installing Trakt but it didn't help. 

JF error code: "_An error occurred when trying to authorize device: 500 - Internal Server Error_"

Log:
https://pastebin.com/cZTEce5E

JF Server: 10.8.4
Trakt: 20.0

**Comment by Shadowghost** [comment] 2022-10-18 08:07
Duplicate of #176 caused by #174 and fixed by #175

**Closed by Shadowghost** 2022-10-18 08:07 UTC
