### ISSUE TITLE
Scheduled task sync fails immediately, but after-playback and mark-as-watched sync work

### ISSUE THREAD

**Issue by bzzbrr** [jellyfin/jellyfin-plugin-trakt#153] opened 2022-06-24 16:18 UTC
### Environment:
Jellyfin version: 10.8
Trakt plugin version: 19.0.0.0
Installation: official docker container, config originally dates to 10.6
Browser: Firefox 101
Installed Plugins: default + playback reporting, reports, tvdb, tvmaze, trakt, open subtitles

### Issue:
Running the "Export library to trakt.tv" scheduled task (in this case manually, but also when scheduled) results in immediate failure and the below error messages in log.  The 500 error suggests trakt server issues, but marking an episode as watched or watching an episode until complete both sync correctly.

A suspicious behavior is that I have 3 users, and intend only to sync the watch status of the alphabetical last user.  When I force re-authorize the trakt plugin, that user is listed as authorized, but so is the 2nd user (and they were de-authorized previously).  The 1st user remains de-authorized at this point.

### Jellyfin logs:
Log shows force re-authorization followed by manual scheduled task execution.
```[2022-06-24 10:17:18.651 -04:00] [INF] [20] Trakt.Api.TraktController: TraktDeviceAuthorization request received
[2022-06-24 10:17:18.774 -04:00] [INF] [47] Trakt.Api.TraktApi: Polling for access token every 5s. Expires at 06/24/2022 14:27:18 UTC.
[2022-06-24 10:17:18.807 -04:00] [INF] [20] Trakt.Api.TraktController: TraktPollAuthorizationStatus request received
[2022-06-24 10:17:29.036 -04:00] [INF] [47] Trakt.Api.TraktApi: Device successfully authorized
[2022-06-24 10:17:29.047 -04:00] [WRN] [20] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://local.ip:8096/Trakt/Users/a37a39e870b4466694f0d4d3bcb26bd0/PollAuthorizationStatus" to "192.168.1.168" in 0:00:10.2445398 with Status Code 200

[2022-06-24 10:18:06.228 -04:00] [INF] [47] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Export library to trakt.tv"
[2022-06-24 10:18:06.229 -04:00] [ERR] [47] Trakt.Api.TraktApi: Tried to reauthenticate with Trakt, but no refreshToken was available
[2022-06-24 10:18:06.288 -04:00] [ERR] [66] Trakt.ScheduledTasks.SyncLibraryTask: Exception handled in SyncMovies
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
[2022-06-24 10:18:06.290 -04:00] [ERR] [66] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-06-24 10:18:06.291 -04:00] [INF] [66] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Failed after 0 minute(s) and 0 seconds
[2022-06-24 10:18:06.294 -04:00] [INF] [66] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

###Plugin Settings
![image](https://user-images.githubusercontent.com/73036314/175575684-c5f1186a-28e0-44d0-b120-b43e641dadb9.png)

**Comment by FranckRJ** [comment] 2022-07-01 09:05
Same issue as you.

I have 4 users but only logged to trakt with one user (the 3rd). The plugin think the 2nd user is also logged to trakt.

When a scheduled task execute, it'll try to sync the trakt state with all users, and if one of them fails then it'll just abort the whole process https://github.com/jellyfin/jellyfin-plugin-trakt/blob/dbf0a55657a431c9cd2ad77e0cd4694c2ace6043/Trakt/ScheduledTasks/SyncFromTraktTask.cs#L106=

The issue is that the plugin incorrectly think that the 2nd user is logged to trakt, so it will try to sync the play states but fails and then the 3rd user that is really logged to trakt won't be able to sync the play states because the task already failed.

I tried to click on "de-authorize" for the 2nd user, it changed the UI (I don't see the button anymore) but it changed nothing for the task, it still try the synchronize the play states even after I clicked on "de-authorize".

**Comment by Shadowghost** [comment] 2022-07-01 23:28
This might be caused by corrupted user date (especially missing refresh keys and other settings) - please reauth all users and try again. If the issue persists logs are appreciated.

**Comment by bzzbrr** [comment] 2022-07-02 00:17
Yep, I force de-authorized and re-authorized every time I was testing.  It was until I deleted the "1st" user that it made any difference.

Here's a log, just after I deleted the first user.  You can see it still fails with the 0 second task (manually executed), then I deauth + reauth, and that combined with only having 2 users works.  

```
[2022-07-01 10:56:43.150 -04:00] [INF] [50] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Failed after 0 minute(s) and 0 seconds
[2022-07-01 10:56:43.152 -04:00] [INF] [50] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks

[2022-07-01 10:57:22.210 -04:00] [INF] [50] Trakt.Api.TraktController: TraktDeviceDeauthorization request received
[2022-07-01 10:57:22.211 -04:00] [ERR] [50] Trakt.Api.TraktApi: Tried to reauthenticate with Trakt, but no refreshToken was available
[2022-07-01 10:57:25.272 -04:00] [INF] [136] Trakt.Api.TraktController: TraktDeviceDeauthorization request received
[2022-07-01 10:57:28.053 -04:00] [INF] [40] Trakt.Api.TraktController: TraktDeviceAuthorization request received
[2022-07-01 10:57:28.116 -04:00] [INF] [50] Trakt.Api.TraktApi: Polling for access token every 5s. Expires at 07/01/2022 15:07:28 UTC.
[2022-07-01 10:57:28.139 -04:00] [INF] [112] Trakt.Api.TraktController: TraktPollAuthorizationStatus request received
[2022-07-01 10:57:38.237 -04:00] [INF] [40] Trakt.Api.TraktApi: Device successfully authorized

[2022-07-01 10:57:38.248 -04:00] [WRN] [112] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://local.ip:8096/Trakt/Users/XXX/PollAuthorizationStatus" to "192.168.1.X" in 0:00:10.1129903 with Status Code 200
[2022-07-01 10:57:55.906 -04:00] [INF] [87] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Export library to trakt.tv"
[2022-07-01 10:57:58.177 -04:00] [INF] [40] Trakt.ScheduledTasks.SyncLibraryTask: Episodes to "add to" collection 2730
[2022-07-01 10:57:58.698 -04:00] [ERR] [40] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "253573", Tvrage: null, Imdb: "tt1898069", Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:58:05.433 -04:00] [ERR] [40] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "8624390", Tvrage: null, Imdb: null, Tmdb: null, Trakt: null, Slug: null } }

[2022-07-01 10:58:15.721 -04:00] [ERR] [136] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-07-01 10:58:15.724 -04:00] [ERR] [136] Trakt.ScheduledTasks.SyncLibraryTask: Exception handled sending episodes to trakt.tv
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendLibraryUpdateInternalAsync(IEnumerable`1 episodes, TraktUser traktUser, EventType eventType, CancellationToken cancellationToken, Boolean useProviderIds)
   at Trakt.Api.TraktApi.SendLibraryUpdateAsync(ICollection`1 episodes, TraktUser traktUser, EventType eventType, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SendEpisodeCollectionUpdates(Boolean collected, TraktUser traktUser, List`1 episodes, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)

[2022-07-01 10:58:15.735 -04:00] [INF] [136] Trakt.ScheduledTasks.SyncLibraryTask: Episodes to set ""watched: 1863
[2022-07-01 10:58:41.713 -04:00] [ERR] [42] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "302938", Tvrage: null, Imdb: "tt4647692", Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:58:45.488 -04:00] [ERR] [40] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "302938", Tvrage: null, Imdb: "tt4647692", Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:58:45.488 -04:00] [ERR] [40] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "302938", Tvrage: null, Imdb: "tt4647692", Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:58:50.308 -04:00] [ERR] [42] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "7460333", Tvrage: null, Imdb: null, Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:58:50.308 -04:00] [ERR] [42] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "7460334", Tvrage: null, Imdb: null, Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:59:06.672 -04:00] [ERR] [112] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "9125827", Tvrage: null, Imdb: null, Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:59:06.673 -04:00] [ERR] [112] Trakt.ScheduledTasks.SyncLibraryTask: Episode not found on trakt.tv: TraktEpisode { Season: 0, Number: 0, Title: null, Ids: TraktEpisodeId { Tvdb: "9063159", Tvrage: null, Imdb: null, Tmdb: null, Trakt: null, Slug: null } }
[2022-07-01 10:59:10.002 -04:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Completed after 1 minute(s) and 14 seconds
[2022-07-01 10:59:10.003 -04:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks```

(The empty lines in the log are just for logical clarity).

**Comment by Shadowghost** [comment] 2022-07-02 07:33
That's correct. You can check the current active version within the dashboard.

According to [Trakt API docs](https://trakt.docs.apiary.io/#introduction/status-codes) 500 errors are reserved to server errors. If soemthing we send is wrong we should get a `400` error back from the API. So I kinda doubt this is can be fixed on our end.

**Comment by FranckRJ** [comment] 2022-07-02 08:59
As I said before, the plugin is trying to execute the scheduled tasks for an user that isn't logged to trakt.tv, so it probably send random data to trakt.tv ence the 500 error they return. The bug is on the plugin side, it shouldn't execute the scheduled tasks for users that don't have a trakt.tv account.

**Comment by FranckRJ** [comment] 2022-07-02 09:08
Ok maybe I misread the logs on my side, I'll send you what I have.

My 2nd user (in alphabetical order):
![image](https://user-images.githubusercontent.com/7328335/176993977-61616a84-b647-48f3-b296-19f49d5b0b36.png)

My 3rd user (in alphabetical order):
![image](https://user-images.githubusercontent.com/7328335/176994008-de59da12-6d11-4907-93d5-31b19cf77828.png)

```
[2022-07-02 11:01:55.596 +02:00] [INF] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Import watched states and playback progress from trakt.tv"
[2022-07-02 11:01:55.659 +02:00] [ERR] [34] Trakt.ScheduledTasks.SyncFromTraktTask: Exception handled
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpClient httpClient, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, IProgress`1 progress, Double percentPerUser, CancellationToken cancellationToken)
[2022-07-02 11:01:55.794 +02:00] [ERR] [34] Trakt.ScheduledTasks.SyncFromTraktTask: Error syncing trakt.tv data for user "Ch**********"
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpClient httpClient, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, IProgress`1 progress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncFromTraktTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
[2022-07-02 11:01:55.797 +02:00] [ERR] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpClient httpClient, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, IProgress`1 progress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncFromTraktTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-07-02 11:01:55.822 +02:00] [INF] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Import watched states and playback progress from trakt.tv" Failed after 0 minute(s) and 0 seconds
[2022-07-02 11:01:55.825 +02:00] [INF] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

As you can see, there is an error for the user "Ch*******", which isn't connected to trakt.tv. But it isn't a 500 error this time it's another one about date range or something.

**Comment by FranckRJ** [comment] 2022-07-02 09:11
I'm pretty sure that yesterday I had the same 500 error as OP, maybe I did something that fixed the error. I think I just de-authorized my 2nd user (that was wrongly considered as authorized after I authorized my 3rd user) and restarted the server.

**Comment by Shadowghost** [comment] 2022-07-02 10:35
You can check `/var/lib/jellyfin/plugins/configurations/Trakt.xml` for all users considered by the Trakt plugin.

**Comment by FranckRJ** [comment] 2022-07-02 10:37
I see 4 entries, I guess one for each users. But only one have an AccessToken and RefreshToken, I guess it's the user "Fr*****" (because in web interface it's the only one I see that is authorized).

**Comment by Shadowghost** [comment] 2022-07-02 10:42
In theory there should only ever be users which are authorized. I guess this might be the problem after all. If you save the settings for a user which is not authorized it still appears in the user list which the plugin uses. I guess an additional check should solve that.

**Comment by FranckRJ** [comment] 2022-07-02 12:42
You're right, I removed every other users from the .xml and now it works, thanks.

**Comment by Appoxo** [comment] 2022-07-21 17:31
> You're right, I removed every other users from the .xml and now it works, thanks.

Can confirm. Deleting/redoing the Trakt.xml has fixed the scheduled tasks bug.
Environment: 
Version: 10.8.1
Operating System: Linux with Docker (LSIO)
Distro: Debian
Architecture: X64

**Closed** 2022-07-25 17:22 UTC
