### ISSUE TITLE
The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')

### ISSUE THREAD

**Issue by JRDevo** [jellyfin/jellyfin-plugin-trakt#163] opened 2022-08-29 16:07 UTC
Hello!

I seem to be getting an error when trying to "Export Library to trakt.tv" using the scheduled job:

Os: Windows 11
Jellyfin: 10.8.4
Trakt Plugin: 19.0.0.0

![image](https://user-images.githubusercontent.com/42043842/187244230-237aadf1-cb0a-402c-ad56-0c880cd2b39a.png)
![image](https://user-images.githubusercontent.com/42043842/187244509-47338a9e-424f-4693-a913-d5eb0452427d.png)

```
[2022-08-29 17:45:24.503 +02:00] [INF] [72] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-08-29 17:45:30.436 +02:00] [INF] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Export library to trakt.tv"
[2022-08-29 17:45:30.446 +02:00] [ERR] [64] Trakt.ScheduledTasks.SyncLibraryTask: Exception handled in SyncMovies
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpClient httpClient, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
[2022-08-29 17:45:30.450 +02:00] [ERR] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpClient httpClient, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-08-29 17:45:30.454 +02:00] [INF] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Failed after 0 minute(s) and 0 seconds
[2022-08-29 17:45:30.457 +02:00] [INF] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

Appreciate the help :)

**Comment by crobibero** [comment] 2022-08-30 12:06
Duplicate of https://github.com/jellyfin/jellyfin-plugin-trakt/issues/45

**Closed by crobibero** 2022-08-30 12:06 UTC
