### ISSUE TITLE
[bug] Getting several errors after adding new content.

### ISSUE THREAD

**Issue by WibblyGhost** [jellyfin/jellyfin-plugin-trakt#126] opened 2022-04-24 20:49 UTC
Tried to run a manual Trakt sync and it keeps spitting out several different errors. Any help in diagnosing this issue?
I have both _watched_ and _unwatched_ import states marked in the settings, and have debug logging enabled. Only started happening after adding new media to my server.

```
[2022-04-25 08:37:51.946 +12:00] [INF] "Scan Media Library" Completed after 1 minute(s) and 46 seconds
[2022-04-25 08:37:51.947 +12:00] [INF] ExecuteQueuedTasks
[2022-04-25 08:37:55.086 +12:00] [INF] Watching directory /home/jellyserver/media/SnowyTv
[2022-04-25 08:38:00.827 +12:00] [INF] Watching directory /home/jellyserver/media/SnowyMovies
[2022-04-25 08:39:15.971 +12:00] [INF] Executing "Sync library to trakt.tv"
[2022-04-25 08:39:16.247 +12:00] [ERR] Error
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-04-25 08:39:16.249 +12:00] [INF] "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds
[2022-04-25 08:39:16.253 +12:00] [INF] ExecuteQueuedTasks
[2022-04-25 08:39:19.679 +12:00] [INF] Executing "Sync library to trakt.tv"
[2022-04-25 08:39:21.129 +12:00] [INF] Movies to add to Collection: 1
[2022-04-25 08:39:21.370 +12:00] [ERR] Exception handled sending movies to trakt.tv
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendLibraryUpdateAsync(IList`1 movies, TraktUser traktUser, CancellationToken cancellationToken, EventType eventType)
   at Trakt.ScheduledTasks.SyncLibraryTask.SendMovieCollectionUpdates(Boolean collected, TraktUser traktUser, List`1 movies, ISplittableProgress`1 progress, CancellationToken cancellationToken)
[2022-04-25 08:39:21.372 +12:00] [INF] Movies to set watched: 0
[2022-04-25 08:39:21.372 +12:00] [INF] Movies to set unwatched: 0
[2022-04-25 08:39:26.090 +12:00] [INF] Episodes to add to Collection: 131
[2022-04-25 08:39:29.088 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0182576", tmdb: null, tvdb: null, tvrage: 3506, trakt: null, slug: null } }
[2022-04-25 08:39:29.088 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0182576", tmdb: null, tvdb: null, tvrage: 3506, trakt: null, slug: null } }
[2022-04-25 08:39:29.088 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0182576", tmdb: null, tvdb: null, tvrage: 3506, trakt: null, slug: null } }
[2022-04-25 08:39:29.088 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0149460", tmdb: null, tvdb: 73871, tvrage: 3628, trakt: null, slug: null } }
[2022-04-25 08:39:29.089 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0149460", tmdb: null, tvdb: 73871, tvrage: 3628, trakt: null, slug: null } }
[2022-04-25 08:39:29.089 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0149460", tmdb: null, tvdb: 73871, tvrage: 3628, trakt: null, slug: null } }
[2022-04-25 08:39:29.089 +12:00] [ERR] TraktResponse not Found: TraktEpisode { season: null, number: null, title: null, ids: TraktEpisodeId { imdb: "tt0149460", tmdb: null, tvdb: 73871, tvrage: 3628, trakt: null, slug: null } }
[2022-04-25 08:39:29.089 +12:00] [INF] Episodes to set watched: 0
[2022-04-25 08:39:29.089 +12:00] [INF] Episodes to set unwatched: 72
[2022-04-25 08:39:36.698 +12:00] [ERR] Error updating episode play states
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.ScheduledTasks.SyncLibraryTask.LogTraktResponseDataContract(TraktSyncResponse dataContract)
   at Trakt.ScheduledTasks.SyncLibraryTask.SendEpisodePlaystateUpdates(Boolean seen, TraktUser traktUser, List`1 playedEpisodes, ISplittableProgress`1 progress, CancellationToken cancellationToken)
[2022-04-25 08:39:36.704 +12:00] [ERR] Tried to reauthenticate with Trakt, but no refreshToken was available
[2022-04-25 08:39:37.752 +12:00] [ERR] Error
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-04-25 08:39:37.754 +12:00] [INF] "Sync library to trakt.tv" Failed after 0 minute(s) and 18 seconds
[2022-04-25 08:39:37.756 +12:00] [INF] ExecuteQueuedTasks
```

**Comment by Shadowghost** [comment] 2022-04-24 20:55
Duplicate of #121 #92 and others.
See https://github.com/jellyfin/jellyfin-plugin-trakt/issues/79#issuecomment-881267918 for how to fix it.
Should be properly handled in v16 of the plugin on jellyfin 10.8

**Closed by Shadowghost** 2022-04-24 20:55 UTC
